### ISSUE TITLE
Payload received in iOS appears to be missing information

### ISSUE THREAD

**Issue by chrisweight** [urbanairship/urbanairship-cordova#224]
Hi there, we're seeing some odd behaviour on iOS using the SDK.

Using latest Phonegap / Cordova SDK, sending the same Push Notification to iOS and Android, the notification is received on both.

On Android, we can see the `extras` stanza is populated appropriately.

On iOS we only appear to get `com.urbanairship.metadata` in the extras stanza. All other information is missing.

iOS version tested is 11.3.1.
SDK version is: 7.0.1

I should note that on both platforms the actual notification displayed is correct - so the information is coming through to the device, it would appear that the SDK is not parsing it correctly at some point on iOS.

<img width="1920" alt="screen shot 2018-05-24 at 14 26 07" src="https://user-images.githubusercontent.com/468638/40488451-b92561e0-5f5e-11e8-99ff-623246c6c0a7.png">

**Comment by rlepinski** [comment]
The device payloads are different so the "extras" come out differently. What info do you need in the event?

**Comment by chrisweight** [comment]
Hi @rlepinski - I would expect to have the title, summary etc available in the iOS event payload as well, given that it's displayed by the OS when the PN arrives?

**Comment by chrisweight** [comment]
@rlepinski - verified the information _is_ coming through to device, but not in the event payload delivered to the handler in-app

**Comment by rlepinski** [comment]
@chrisweight should be fixed in 7.1.0
