### ISSUE TITLE
SDK Documentation Not Available Now?

### ISSUE THREAD

**Issue by gonzalovinas** [urbanairship/urbanairship-cordova#241]
Hi there,

I was reading https://docs.urbanairship.com/reference/libraries/urbanairship-cordova/latest/index.html 

and when trying to read about the PUSH event (at the bottom  in gray) its redirects me to https://docs.urbanairship.com/reference/libraries/urbanairship-cordova/latest/UrbanAirship.html#event:push 

whichs is a "Aww Snap! The page you requested could not be found."

**Comment by rlepinski** [comment]
Looks like we have an issue with the generate docs. You can look at the [source](https://github.com/urbanairship/urbanairship-cordova/blob/7.1.1/www/UrbanAirship.js#L170) to see the doc comments. We will try to get it fixed in the next release.

**Comment by rlepinski** [comment]
Should be fixed: https://docs.urbanairship.com/reference/libraries/urbanairship-cordova/latest/module-UrbanAirship.html#~event:push
