### ISSUE TITLE
Android crash when in background

### ISSUE THREAD

**Issue by wilsolutions** [urbanairship/urbanairship-cordova#247]
Hi, please, I'm getting 2 crashing messages using UA 6.9.3 with cordova 6.5.0.
Here you are the details:

### What version of urbanairship-cordova are you using?
6.9.3

### Is your issue affecting the Android platform, iOS platform, or both?
Android

### What version of cordova-ios and/or cordova-android are you using?
cordova --version
  6.5.0
Installed platforms:
  android 6.3.0
  ios 4.5.4

### What are the versions of any relevant development tools you are using?
ionic v1

# Report

### What unexpected behavior are you seeing?
A popup saying that appears when the App is in background saying that it has crashed.

### What is the expected behavior?
No popups about crashing

### What are the steps to reproduce the unexpected behavior?
Just install the App, put in background and wait a few minutes or look at the crash logs.

### Do you have logging for the issue?
https://gist.github.com/wilsolutions/3833ae90a8f0c737638816c6a5d9c46c

**Comment by rlepinski** [comment]
I believe both your issues are fixed if you update to the latest plugin version.

**Comment by wilsolutions** [comment]
Hi rlepinski, thank you for the quick response.

Yeah, but upgrading would require to upgrade to Cordova 8 and unfortunately would lead to other issues :( 

Maybe is time to get some time and face these issues lol...

tkx man
