### ISSUE TITLE
Can't re-enable notifications

### ISSUE THREAD

**Issue by pbirsinger** [urbanairship/urbanairship-cordova#249]
Hi, I am unable to find a way to re-enable notifications on IOS after a user turns them off in notification center. I call ```UAirship.setUserNotificationsEnabled(true)``` and get a success callback, but no prompt opens for the user to re-enable. Is there a way to do this, or do I just need to link to the notification center for my app (how?)? Thanks.

### What version of urbanairship-cordova are you using?
ℹ Please include relevent version here.
newest version
### Is your issue affecting the Android platform, iOS platform, or both?
ℹ Please include affected platforms here.
ios
### What version of cordova-ios and/or cordova-android are you using?
ℹ Please include relevent versions here.
latest

**Comment by rlepinski** [comment]
Thats how Apple's APIs work. You only have one chance to prompt them in the app, after that you have to direct them to the system settings for the app.

**Comment by pbirsinger** [comment]
Thanks. Does this plugin have or plan on having any feature to direct them to system settings for app?
