### ISSUE TITLE
iOS app does not receive push notifications in development mode when installed from TestFlight

### ISSUE THREAD

**Issue by connor-odoherty** [urbanairship/urbanairship-cordova#252]
# Preliminary Info

### What version of urbanairship-cordova are you using?
7.2.0

### Is your issue affecting the Android platform, iOS platform, or both?
iOS

### What version of cordova-ios and/or cordova-android are you using?
4.5.5

### What are the versions of any relevant development tools you are using?
Ionic CLI 4.1.1

# Report

### What unexpected behavior are you seeing?

I have in_production set to false on dev build of my app. I have downloaded this dev binary from TestFlight. When I first log in to the app, the device token is properly registered to the name user. When I go into the UrbanAirship dashboard, I see that user registered, along with the three green lights indicating that the device is ready to receive push notifications.

However, when I send a push notification from the dashboard, I do not see the push notification on the device. In addition, when I go back to look at the named user, it now says 'no devices' instead of the three green lights.

Some things to note:
* If I build this exact same binary through xCode onto the device, everything works as expected
* If I change in_production to TRUE and use my prod account, everything works fine when the app is downloaded through TestFlight

Is this by design? Is UrbanAirship treating all TestFlight downloaded apps as production builds? If thats the case, why am I able to successfully register with development credentials at first?

### What is the expected behavior?
The ability to use development credentials to send and receive push notifications when downloaded from TestFlight

### What are the steps to reproduce the unexpected behavior?
Described above

**Comment by crow** [comment]
@connor-odoherty someone will be looking into this shortly, thanks for reporting.

**Comment by crow** [comment]
Test Flight is integrated with the app store and requires applications to use app store provisioning. Urban Airship will detect that your app is provisioned with an App Store provisioning profile and require that it use the Urban Airship production environment.
