### ISSUE TITLE
QUESTION: What steps would need to be taken to build against Cordova Android 6.4.0 ?

### ISSUE THREAD

**Issue by chrisweight** [urbanairship/urbanairship-cordova#256]
# Preliminary Info

### What version of urbanairship-cordova are you using?
ℹ Currently 7.0.1

### Is your issue affecting the Android platform, iOS platform, or both?
ℹ Android

### What version of cordova-ios and/or cordova-android are you using?
ℹ 6.4.0

### What are the versions of any relevant development tools you are using?
ℹ N/A

# Report

Would you be able to highlight any particular steps required to allow building the latest version of the plugin against `cordova-android@6.4.0`

**Comment by rlepinski** [comment]
Here is the commit that probably broke 6.4.0 support - https://github.com/urbanairship/urbanairship-cordova/commit/675b0ca85ece7c42c0f8c7b736204d3ea076de28

Basically you just need to apply the google-services plugin at the end of your build.gradle. How you do that is up to you. You could probably provide a build-extras.gradle file to accomplish that.

**Comment by chrisweight** [comment]
Cheers @rlepinski - I'll take a look at that - v helpful
