### ISSUE TITLE
No Sound/Vibrate when Push Notification arrives on iOS

### ISSUE THREAD

**Issue by gonzalovinas** [urbanairship/urbanairship-cordova#263]
Using urbanairship-cordova 7.0.1 when push notification arrives, its default "tipical" sound plays OK on android but not on iOS. Neither vibrates.

iphone is 5s running 11.4.1 and iphone 6 running 12 -- same behaviour both.

ios version compiled under macOS 9.4

payload for HTTP Push Server is as follow:

var payload = {
                   "audience": {
                     "channel": channel_id 
                    },
                   "device_types" : [ "ios", "android" ],
                   "notification" : {
                      "ios" : {
                        "badge": "+1",
                         "alert" : msg,
                        "extra": { customField: topicoPush }
                      },
                      "android": {
                          "alert" : msg,
                         "extra": { customField: topicoPush }
                      },
                      "actions": {
                        "open": {
                            "type": "deep_link",
                            "content": topicoPush
                        }
                      }
                   }
                };

I started to think if every worked... :S

any clues?

thanks in advance

**Comment by rlepinski** [comment]
What version of Android? For 8.0+ you now have to set channels, the vibrate, sound, and quiet time interval no longer work for those devices.

For iOS, you need to[ define a sound](https://docs.urbanairship.com/api/ua/#schemas/iosoverrideobject/sound). Using `default` works if you do not have a custom sound.

**Comment by gonzalovinas** [comment]
Android 7.1 ... but it is working just fine!!

I add "sound" : "1" to the ios part of the payload.. and now its working!! 

thanks for the api doc ref!
