### ISSUE TITLE
Picture on push notification working on Android but NOT on iOS 

### ISSUE THREAD

**Issue by gonzalovinas** [urbanairship/urbanairship-cordova#264]
Using urbanairship-cordova 7.0.1 I can send pictures as push notifications on Android, but not on iOS 11.4 on a iphone 5s. 

Is UA Media Attachment related to ? should I do anything else in xCode to let pictures show on iPhone ?

HTTP payload is as follows:

var payload = {
                   "audience": {
                     "channel": channel_id 
                    },
                   "device_types" : [ "ios", "android" ],
                   "notification" : {
                      "ios" : {
                        "badge": "+1",
                         "alert" : msg,
                         "sound": "1", //"alarmfired.mp3", // or default "1"
                        "extra": { customField: topicoPush },
                         "media_attachment": {
                             "content": {
                                 "body": "Hello",
                             "subtitle": "xxx",
                             "title": "yyyy"
                             },
                             "url": "https://media.giphy.com/media/l2YSgdn0tmvotdOFy/giphy.gif"
                         }
                        },
                      "android": {
                          "alert" : msg,
                          "sound": "alarmfired", 
                          "style": {
                              "type": "big_picture",
                              "big_picture": "https://media.giphy.com/media/l2YSgdn0tmvotdOFy/giphy.gif",
                              "title": "Paso",
                              "summary": "Todo"
                          },
                         "extra": { customField: topicoPush }
                      },                     
                      "actions": {
                        "open": {
                            "type": "deep_link",
                            "content": topicoPush
                        }
                      }
                   }
                };

Thanks in advance.

**Comment by rlepinski** [comment]
You need the [notification service extension](https://docs.urbanairship.com/platform/ios/#notification-service-extension). We have not found a way to automate setting it up for a cordova app, so you have to do it manually by modifying the generated xcode project. Ill add a snippet to the readme.
