### ISSUE TITLE
Failling to install version 7.3.1

### ISSUE THREAD

**Issue by Chuckytuh** [urbanairship/urbanairship-cordova#265]
# Preliminary Info

### What version of urbanairship-cordova are you using?

Attempting to install version 7.3.1

### Is your issue affecting the Android platform, iOS platform, or both?

Both

### What version of cordova-ios and/or cordova-android are you using?

cordova-cli: 7.1.0
cordova-android: 6.4.1
cordova-ios: 4.3.1

# Report

### What unexpected behavior are you seeing?

When attempting to install the plugin, specifically the version 7.3.1 from npm, the version 7.3.0 is being fetched and the install fails with the following message:

`Error: Expected plugin urbanairship-cordova to satisfy version "7.3.1" but got "7.3.0".`

### What is the expected behavior?

Plugin would install specified version given that's the one published on npm.

### What are the steps to reproduce the unexpected behavior?

Create a cordova project
`cordova plugin add urbanairship-cordova@7.3.1`

**Comment by Chuckytuh** [comment]
It seems to be related with the fact that the plugin has been published on npm with the version package.json to be 7.3.1 however, on plugin.xml, the plugin is till version 7.3.0 that causes the error mentioned on the issue!

**Comment by rlepinski** [comment]
Unable to republish the package so I am prepping a 7.3.2 release

**Comment by rlepinski** [comment]
Released 7.3.2
