### ISSUE TITLE
Missing import statement

### ISSUE THREAD

**Issue by Chuckytuh** [urbanairship/urbanairship-cordova#268]
# Preliminary Info

On line [91 from UAirshipPlugin.java](https://github.com/urbanairship/urbanairship-cordova/blob/master/src/android/UAirshipPlugin.java#L91) , AutoPilot is being referenced however, there's no import statement for that class which causes compilation to fail for Android.

### What version of urbanairship-cordova are you using?

7.3.1+

### Is your issue affecting the Android platform, iOS platform, or both?

Android

### What version of cordova-ios and/or cordova-android are you using?
cordova-cli: 7.1.0
cordova-android: 6.4.0

# Report

### What unexpected behavior are you seeing?
Android build fails.

### What is the expected behavior?
Android build succeeds :)

### What are the steps to reproduce the unexpected behavior?
```
$ cordova create ...
$ cordova plugin add urbanairship-cordova
$ cordova build
```

**Comment by rlepinski** [comment]
Released 7.3.3. Sorry for the wait.
