### ISSUE TITLE
GCM obsolescence April 2019 coming soon

### ISSUE THREAD

**Issue by gonzalovinas** [urbanairship/urbanairship-cordova#276]
Hi there guys! I wonder how to check what cordova plugin version matches urbanairship SDK version 9.1.0 as stated in this article?  https://docs.urbanairship.com/whats-new/2018-04-26-gcm-deprecation

I'm sing urbanairship-cordova 7.0.1 and its all working fine.. do I have to update something else?

Thanks in advance!

**Comment by rlepinski** [comment]
We usually list the SDK versions in the Changelog - https://github.com/urbanairship/urbanairship-cordova/blob/master/CHANGELOG. We actually switched over to FCM in plugin version 7.1.0. See the README for how to include the google-services.json file.
