### ISSUE TITLE
Notification Sound Volume

### ISSUE THREAD

**Issue by gonzalovinas** [urbanairship/urbanairship-cordova#279]
Hi there guys,

I`m trying to figure out if notification sound volume can be controlled in such a way to be as loud as possible even when the phone is muted or or with low volume.

It's an alarm requirement.

Thanks in advance!

**Comment by marc-scig** [comment]
@gonzalovinas as far as I know this is not possible. Volume is not one of the configurable notification options, although iOS does have a new feature as of 12 that allows for apps to send "critical alerts" which supposedly bypasses normal device settings. However these are for real emergencies, not everyday alarm type apps, so Apple is very stingy about giving out provisioning for this. I'm going to mark this as closed, and in the future please direct general questions like these to support.
