### ISSUE TITLE
Tips for extending Native Libraries

### ISSUE THREAD

**Issue by gonzalovinas** [urbanairship/urbanairship-cordova#280]
Hi there, I'm looking forward tips about making changes to AirshipReceiver.java to extend core functionality. It could be good for the project itself.

But, I would to know if you can help me giving me some tips about how to package and rebuild cordova package.

Thanks in adnvace, and happy Xmas!!!

**Comment by marc-scig** [comment]
Hi @gonzalovinas,

It would be best to direct questions like these to support, and in the future, please reserve this page for bugs or more specific user issues with the SDK/plugin.

thanks and happy holidays :)
