### ISSUE TITLE
iOS build failed

### ISSUE THREAD

**Issue by shreyasb0912** [urbanairship/urbanairship-cordova#283]
### What version of urbanairship-cordova are you using?
ℹ 7.3.0
### Is your issue affecting the Android platform, iOS platform, or both?
ℹ iOS

### What are the versions of any relevant development tools you are using?
ℹ Outsystems 10 Version 10.0.823.0

# Report

### What unexpected behavior are you seeing?
ℹ iOS build getting failed

### What is the expected behavior?
ℹ iOS build should be created
### What are the steps to reproduce the unexpected behavior?
ℹ Add Urbanairship plugin to the source code and build iOS app. The build fails to succeed.

### Do you have logging for the issue?
ℹ Please provide links to gists of any pertinent logs here.
[iOSBuildLog.txt](https://github.com/urbanairship/urbanairship-cordova/files/2769239/iOSBuildLog.txt)

Does the latest version of Urbanairship plugin works on Xcode 9 ?

**Comment by rlepinski** [comment]
We require Xcode 10 for the latest plugin. It supports iOS 12 features.

The build log does not contain anything specific to Urban Airship. If you are not using Xcode 10 that is probably the issue but I have no way of knowing if thats the only issue based on the log.

**Comment by BrianBatchelder** [comment]
@shreyasb0912 : Your build log contains the following line: `An unexpected error has occurred while generating your application. Please try again. If the problem persists, contact OutSystems Support.`. As we don't formally support OutSystems, I suggest you contact them.
