### ISSUE TITLE
src/ios/Airship/libUAirship-10.0.3.a not found

### ISSUE THREAD

**Issue by umeshk** [urbanairship/urbanairship-cordova#284]
# Please fill out this template when submitting an issue.
All lines beginning with an ℹ symbol indicate information that's important for you to provide to ensure your issue is resolved as quickly and efficiently as possible.

❗For how-to inquiries involving Urban Airship functionality or use cases, please
contact (support)[https://support.urbanairship.com/hc/en-us].

# Preliminary Info

### What version of urbanairship-cordova are you using?
ℹ 7.4.0.

### Is your issue affecting the Android platform, iOS platform, or both?
ℹ iOS.

### What version of cordova-ios and/or cordova-android are you using?
ℹ Outsystems 10 Version 10.0.823.0

### What are the versions of any relevant development tools you are using?
ℹ If applicable, please include any other relevant information about the version of your
IDE, plugin(s), or package manager(s) here.

# Report

### What unexpected behavior are you seeing?
ℹ  iOS build getting failed

### What is the expected behavior?
ℹ  iOS build getting failed

### What are the steps to reproduce the unexpected behavior?
ℹ   Add Urbanairship plugin to the source code and build iOS app. The build fails to succeed.

### Do you have logging for the issue?
ℹ Please provide links to gists 
[iOSBuildLog.txt](https://github.com/urbanairship/urbanairship-cordova/files/2782450/iOSBuildLog.txt)
of any pertinent logs here.

**Comment by BrianBatchelder** [comment]
@umeshk : We do not have formal support for Outsystems. From your log, I can't tell where the build is getting our plugin from. The NPM version does include `libUAirship-10.0.3.a`.

You might try running following our generic Cordova instructions, especially `cordova plugin add urbanairship-cordova` to add the Urban Airship Cordova Plugin to your project. Once you do that, `libUAirship-10.0.3.a` should be found at the path in your log and appear in the "Link Binaries With Libraries" build phase in Xcode.

Please let us know if you have further issues.

**Comment by umeshk** [comment]
@BrianBatchelder thanks for your reply. We installed the plugin and libUAirship-10.0.3.a is present now. But size of that file is around 100MB. Why is that so big?

**Comment by umeshk** [comment]
@BrianBatchelder also we got below issue
android/src/com/urbanairship/cordova/UAirshipPlugin.java:228: error: local variable callbackContext is accessed from within inner class; needs to be declared final
So is this fixed in latest code? We do have latest code.
After adding final keyword on line 209 before CallbackContext it worked fine.

**Comment by umeshk** [comment]
@BrianBatchelder also we found that we are not able to receive push notification when app is closed on android devices.

**Comment by umeshk** [comment]
@BrianBatchelder one more issue found that we are not able to receive push notification when app is open  on iOS devices

**Comment by BrianBatchelder** [comment]
> @BrianBatchelder thanks for your reply. We installed the plugin and libUAirship-10.0.3.a is present now. But size of that file is around 100MB. Why is that so big?

Our static library contains a lot of stuff, only some of which is used by each app. The actual increased download size of an app including our SDK is less than 1 MB (0.8 MB). The increase in app size on the device storage system is 2.1 MB.

> @BrianBatchelder also we got below issue
> android/src/com/urbanairship/cordova/UAirshipPlugin.java:228: error: local variable callbackContext is accessed from within inner class; needs to be declared final
> So is this fixed in latest code? We do have latest code.
> After adding final keyword on line 209 before CallbackContext it worked fine.

We will take a look at this. You are also welcome to submit a PR with your fix.

> @BrianBatchelder also we found that we are not able to receive push notification when app is closed on android devices.
> @BrianBatchelder one more issue found that we are not able to receive push notification when app is open on iOS devices

For questions like this, please contact UA Support at: https://support.urbanairship.com

**Comment by BrianBatchelder** [comment]
@umeshk : Version 7.5.0 of our Cordova plugin was just released. It should address your issues.

**Comment by shreyasb0912** [comment]
@BrianBatchelder : I have installed the latest version of the plugin i.e 7.5.0 but still size of file libUAirship-10.0.3.a is above 100 MB whereas in earlier version of this plugin i.e 7.3.0 the file was of size 1 KB

**Comment by umeshk** [comment]
@BrianBatchelder thanks for updating plugin. My colleague @shreyasb0912 already added comment above for observations we found.

**Comment by BrianBatchelder** [comment]
@shreyasb0912 : Version 7.3.0 of our plugin used version 10.0.0 of our SDK. `libUAirship-10.0.0.a` is 108MB (download [here](
https://bintray.com/urbanairship/iOS/download_file?file_path=urbanairship-sdk%2F10.0.0%2FlibUAirship-10.0.0.zip)). If you are seeing a 1 KB file, something must have gone wrong during your previous build process. 

Regardless of the large size on disk, we assure you that your app's size will only increase as I indicated in my previous comment.
