### ISSUE TITLE
Custom Notification Sound on Android > 8 

### ISSUE THREAD

**Issue by gonzalovinas** [urbanairship/urbanairship-cordova#288]
using version 7.0.1 a working setup using android < 8 works OK but on Android 8 the notification sound does not play.

Should the HTTP API be called somehow different?

**Comment by gonzalovinas** [comment]
I found that adding    "notification_channel": "Notifications" would play default notification sound, but what about the "old?" sound tag?

**Comment by rlepinski** [comment]
Its explained here - https://github.com/urbanairship/urbanairship-cordova/issues/277

We are working on a notification channel compat feature in our SDK. Once that is done we will expose an API to create channels in cordova and completely deprecate the push API feature to set the sound.
