### ISSUE TITLE
Incompatibility with Intercom and Urban Airship on Android

### ISSUE THREAD

**Issue by jskrepnek** [urbanairship/urbanairship-cordova#292]
# Preliminary Info

### What version of urbanairship-cordova are you using?
7.5.1

### Is your issue affecting the Android platform, iOS platform, or both?
Android

### What version of cordova-ios and/or cordova-android are you using?
cordova-android version 7.1.1

### What are the versions of any relevant development tools you are using?
cordova-plugin-intercom version 6.1.0

# Report

### What unexpected behavior are you seeing?
Build fails

### What is the expected behavior?
Build passes

### What are the steps to reproduce the unexpected behavior?
- Clone new Cordova project
- Add both plugins
- Build for Android

### Do you have logging for the issue?

> A problem occurred configuring project ':app'.
> Cannot add task ':app:processDebugGoogleServices' as a task with that name already exists.

**Comment by crow** [comment]
Hey @jskrepnek thanks for the report. Taking a look at this.

**Comment by rlepinski** [comment]
@jskrepnek Could you try setting the config for intercoms push type to 
```
<preference name="intercom-android-push-type" value="fcm-without-build-plugin"/>
```
 and see if that resolves your issues?

**Comment by jskrepnek** [comment]
Thanks @rlepinski - that helped.  Will suggest to Intercom that they document this configuration.
