### ISSUE TITLE
Can't send notifications from other FCM sources

### ISSUE THREAD

**Issue by jskrepnek** [urbanairship/urbanairship-cordova#296]
# Preliminary Info

### What version of urbanairship-cordova are you using?
ℹ 7.5.2

### Is your issue affecting the Android platform, iOS platform, or both?
ℹ Android

### What version of cordova-ios and/or cordova-android are you using?
ℹ cordova-android version 7.1.1

### What are the versions of any relevant development tools you are using?
ℹ cordova-plugin-intercom: 6.2.0

# Report

### What unexpected behavior are you seeing?
ℹ Devices not receiving push notifications from Intercom or from Firebase console when application is in foreground, background or neither.  Successfully able to send notifications to device via Urban Airship via API and with the test push tool.

### What is the expected behavior?
ℹ Can send FCM notifications from all sources.

### What are the steps to reproduce the unexpected behavior?
ℹ Integrate UA with FCM.  Attempt to send notification from Firebase console.

### Do you have logging for the issue?
ℹ No error logs pertaining to this are evident.  UA is successfully registering.

**Comment by marc-scig** [comment]
Hi @jskrepnek,

Are you using the same FCM sender ID across these dashboards? If not, can you share your app configuration?

**Comment by jskrepnek** [comment]
Hi @marc-scig 

Yes, we're using the same FCM configuration for Intercom and Urban Airship (i.e.: google-services.json).  Is that what you mean?

What aspects of our app configuration would be helpful here?

**Comment by marc-scig** [comment]
That was the main thing I was wondering. I know we've had some difficulty in the past with supporting multiple sender addresses, though I think that should be fine now. If you're using the same google-services.json it should just work, but let me confer with my team and see if there's not something obvious here. In the meanwhile, are there any suspicious logs when you try to send from one of those other servcies, perhaps about a message being dropped or rejected?

**Comment by marc-scig** [comment]
Regarding the Firebase Console, It should be possible to send a "notification message" through the firebase console without any conflict. If that doesn't work, I'd supsect a configuation problem within Firebase. However, If you're sending a data message (i.e. something that's received by FirebaseMessagingService) and the push doesn't go through the Urban Airship APIs, the SDK will drop the message when it's received. We don't currently support handling data messages in the SDK that are sent through other platforms, and from the SDK's perspective it has no idea where the message came from if it doesn't contain known UA metadata.. 

However, it is technically possible to  implement a custom FirebaseMessagingService subclass and forward calls to the SDK (see the FCM setup section in https://docs.urbanairship.com/platform/android/). FWIW this appears the be case as well for Intercom (https://developers.intercom.com/installing-intercom/docs/android-fcm-push-notifications).

**Comment by jskrepnek** [comment]
My original report was incorrect with respect to sending notifications from the Firebase Console.  It works fine.

And it looks like you've identified the compatibility problem between UA and Intercom.

Is there a straight forward way to achieve this with the Cordova project, or at least a way if we were to have to fork this repository that it might come back to the mainline?

Thanks for your help on this.

**Comment by rlepinski** [comment]
@jskrepnek The main issue is FCM only supports a single FCM Service and there is no easy way to resolve this due to Android O background limitations. Not sure about an easy way to fix your issue without a direct dependency on intercom which we want to avoid. I think a better idea would be to create a new plugin (not a fork) that depends on both intercom and UA and resolves the FCM Service problem. That would allow you to use an unmodified version of the intercom and ua cordova plugins.

**Comment by jskrepnek** [comment]
@rlepinski Thanks for the investigation and possible fix.

**Comment by jskrepnek** [comment]
@rlepinski Hi again.  I'm going to attempt creating this plugin.  One question is how I go about overriding the UA's extension of the FirebaseMessagingService?  How do I choose our custom one to take priority?

**Comment by jskrepnek** [comment]
@rlepinski I'm also looking at https://docs.airship.com/platform/android/getting-started/#sdk-setup-for-fcm, but the advice doesn't apply to our current version of the UA plugin, 7.6.0, which doesn't have `AirshipFirebaseIntegration`.

**Comment by MaximBelov** [comment]
Solution
cordova-plugin-intercom ^7.1.0"
urbanairship-cordova ^7.6.0
https://github.com/kohofinancial/cordova-plugin-firebase-messaging-extension
______
for
cordova-plugin-intercom "^8.0.0"
urbanairship-cordova "^10.0.0"
cordova-plugin-firebasex "7.0.1"

Extra plugins
cordova-android "8.1.0"
cordova-ios": "5.1.1"
cordova-plugin-androidx "1.0.2",
cordova-plugin-androidx-adapter "1.1.0"
cordova-android-firebase-gradle-release 4.0.0"
cordova-android-play-services-gradle-release "4.0.0"
cordova-android-support-gradle-release "3.0.1"

Android Config:
  <preference name="intercom-android-push-type" value="FCM-WITHOUT-BUILD-PLUGIN"/>

Fix conflict for android 
_uaSkipApplyGoogleServicesPlugin_
https://github.com/urbanairship/urbanairship-cordova/blob/master/src/android/build-extras.gradle#L41

ionic cordova build android --verbose --buildConfig=build.json -- -- --gradleArg=-PuaSkipApplyGoogleServicesPlugin=false

https://github.com/MaximBelov/cordova-plugin-firebase-messaging-extension
https://www.npmjs.com/package/cordova-plugin-firebase-messaging
