### ISSUE TITLE
No way to updateRegistration after namedUser was set

### ISSUE THREAD

**Issue by vste23** [urbanairship/urbanairship-cordova#299]
### What version of urbanairship-cordova are you using?
7.5.3
### Is your issue affecting the Android platform, iOS platform, or both?
iOS
### What version of cordova-ios and/or cordova-android are you using?
7.5.3
### What are the versions of any relevant development tools you are using?
VS Code, UIWebView, Cordova iOS 4.5.5, Cordova 8.1.2, Angular CLI, Angular 7

# Report

### What unexpected behavior are you seeing?
After setting namedUser from js code application starts to receive notifications after app restart. However in native urbanairship you have `updateRegistration` method thats allows to start receiving them immediately after setting namedUser receiver

### What is the expected behavior?
To be able update registration of a namedUser client

### What are the steps to reproduce the unexpected behavior?
Just set named user on iOS and try to receive notification without app restart
### Do you have logging for the issue?
no

**Comment by vste23** [comment]
More info about `updateRegistration` method for native Urban Airship - https://support.urbanairship.com/hc/en-us/articles/213489883-Setting-Named-Users-upon-login

**Comment by rlepinski** [comment]
@vste23 That support article is wrong, setting a named user will update when being assigned. The `updateRegistration` calls are only needed for tags and some other push settings.  If you are interested, here is what the SDK does when the named user is set - https://github.com/urbanairship/ios-library/blob/master/AirshipKit/AirshipKit/common/UANamedUser.m#L88
