### ISSUE TITLE
iOS App crash and null fields on Android

### ISSUE THREAD

**Issue by wilsolutions** [urbanairship/urbanairship-cordova#300]
# Preliminary Info
Push notification issue:
- Crash iOS App
- Display null fields on Android

### What version of urbanairship-cordova are you using?
`urbanairship-cordova 7.5.4`

### Is your issue affecting the Android platform, iOS platform, or both?
both

### What version of cordova-ios and/or cordova-android are you using?
```
cordova-cli 8
cordova-ios 4.5.5
cordova-android 7.1.4

```
### What are the versions of any relevant development tools you are using?
```
cordova-android-disable-aapt2 1.0.0 
cordova-android-firebase-gradle-release 3.0.0 
cordova-android-play-services-gradle-release 3.0.0 
cordova-android-support-gradle-release 3.0.0 
cordova-plugin-customurlscheme 4.4.0 
cordova-plugin-firebase 2.0.5 
phonegap-plugin-barcodescanner 6.0.8 
urbanairship-cordova 7.5.4 
```

# Report

### What unexpected behavior are you seeing?
iOS: put the app in background, send a push notification, tap the notification in the device. Result: App comes to the foreground but crash.

Android: send the push notification, notification does not appear to the use but the logs from logcat display null title, body, etc...

### What is the expected behavior?
As an user i expect to receive a push notification in both platform, tap on it and my App is opened.

### What are the steps to reproduce the unexpected behavior?
Just install an App in both devices and send a push notification.

### Do you have logging for the issue?
Android:
```
From: ******
Notification Message id: 43
Notification Message Title: null
Notification Message Body/Text: null
Notification Message Sound: null
Notification Message Lights: null
```

iOS
```
2019-05-01 12:03:08.405284-0400 [2302:1923459] [D] -[UAInboxMessageList retrieveMessageListWithSuccessBlock:withFailureBlock:] [Line 137] Retrieving message list.
2019-05-01 12:03:08.406976-0400 [2302:1924531] PBItemCollectionServicer connection disconnected.
2019-05-01 12:03:08.418918-0400 [2302:1923459] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[UAAutoIntegrationDummyDelegate delegate]: unrecognized selector sent to instance 0x1c400f100'
*** First throw call stack:
(0x18466ed8c 0x1838285ec 0x18467c098 0x1846745c8 0x18455a41c 0x1010f0720 0x1014d7874 0x1010f0748 0x1014d7874 0x18e27f2b0 0x18e248e88 0x18eede84c 0x18e2481ec 0x18ecc3ac8 0x18ee11bf8 0x18e247c0c 0x18e2475a8 0x18e285334 0x186e70f24 0x1020d519c 0x1020e17cc 0x186ea4878 0x186ea451c 0x186ea4ab8 0x184617404 0x184616c2c 0x18461479c 0x184534da8 0x18651a020 0x18e554758 0x100f7caf0 0x183fc5fc0)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb) 
```

**Comment by rlepinski** [comment]
Are you sending the push through Airship or firebase? Can you provide verbose logs?

**Comment by wilsolutions** [comment]
Hi, thank you for getting back to me.
I'm sending the notification from Airship dashboard.

So, after more investigation I've figured out that the issue is happening in the cordova-firebase, something is broken in the integration. If I remove it UA will works fine.

I've reported the issue:
https://github.com/arnesson/cordova-plugin-firebase/issues/1053

My temporary solution is to commend the delegate portion in iOS and update the message data keys in the Android side to get around the null fields.

```
 0 = "com.urbanairship.push.ALERT"
 1 = "com.urbanairship.metadata"
 2 = "com.urbanairship.push.PUSH_ID"
 3 = "com.urbanairship.title"
 4 = "com.urbanairship.push.APID"
 5 = "com.urbanairship.push.CANONICAL_PUSH_ID"
 6 = "com.urbanairship.summary"
```

I'm really looking forward to have Airship fully working Firebase (FCM), removing the cordova-firebase plugin is not an option to me.

Thank you

**Comment by marc-scig** [comment]
Hi @wilsolutions,

Our plugin is not designed to coexist with other firebase plugins simultaneously. One reason for this, and likely the reason why you're seeing the android issues mentioned above, is that there can only be one `FirebaseMessagingService` class registered at a time, and the `AirshipFirebaseMessagingService` in our plugin normally handles (or delegates) the push processing and bookkeeping that's necessary for the message to make its way through our SDK correctly. It looks like  the `cordova-firebase` plugin you're using has its own messaging service class and is probably intercepting incoming pushes.

It is technically possible to forward messages to the AirshipFirebaseMessagingService and AirshipFirebaseInstanceIdService in native code, as shown [here](https://docs.airship.com/platform/android/getting-started/#sdk-setup-for-fcm), but that would probably require modifying the cordova-firebase plugin. 

My recommendation would instead be to drop that plugin and rethink your assumption as to whether you need two firebase plugins to do what you need. If there are specific features you're depending on that Airship doesn't cover, let us know.

**Comment by wilsolutions** [comment]
Hi @marc-scig thank you for your reply.

The reason I do use Firebase is that I need general analytics events tracking and crashlytics.

**Comment by wilsolutions** [comment]
Alright, I've removed the outdated broken `cordova-plugin-firebase`, now the control is back to Airship. 
Thank you!
