### ISSUE TITLE
push and notification_opened events not firing on iOS 

### ISSUE THREAD

**Issue by chrisweight** [urbanairship/urbanairship-cordova#302]
# Please fill out this template when submitting an issue.
All lines beginning with an ℹ symbol indicate information that's important for you to provide to ensure your issue is resolved as quickly and efficiently as possible.

❗For how-to inquiries involving Urban Airship functionality or use cases, please
contact (support)[https://support.urbanairship.com/hc/en-us].

# Preliminary Info

### What version of urbanairship-cordova are you using?
7.5.4

### Is your issue affecting the Android platform, iOS platform, or both?
iOS only

### What version of cordova-ios and/or cordova-android are you using?
cordova-ios@4.5.5

### What are the versions of any relevant development tools you are using?
ℹXcode 10.2.1

# Report

### What unexpected behavior are you seeing?

Here's the scenario for context: 

- I install our application on two iOS devices (iPhone XR, iPhone 6s). 
- I log in to to the application on each device, using two different user accounts (User A and User B). 
- I enable push notifications on both devices and ensure that both users are registered against UA with Channel ID's correctly identified and showing enabled. 
- Using our app, I make User A a friend of User B (similar to any social networking 'friend request' model). 
- Users are able to make 'support requests' to their friend connections. So, I create a support request from User A to User B. 
- Creating a support request generates an event on our servers, storing the data about that request for retrieval. 
- This subsequently generates a request to the UA API from our servers to send a push notification (in this case, from User A to User B) 
- Any amendments (updates, cancellation etc) to that support request would also generate a server-side push notification request to the UA API. These all follow the same structure and use consistent keys for the type of event that has occurred - whether that is support request creation, amendment or deletion. 
- When the user receives the push notification informing them of the support request being made to them (or any updates to it), they should be able to tap on the notification, this opens the application and then shows the user the support request.

We have a number of different actions that can generate push notification requests to the UA API, the support request scenario is one example. In many cases, we want to direct the user to a different tab in the application, or to show a modal containing information based upon the push notification received.

Our server logs indicate that the requests / responses to the UA API are well formed and correct, we can also see that the notifications are sent to the devices correctly and are displayed on screen as expected.

In some cases, the `urbanairship.push` and `urbanairship.notification_opened`events does not appear to trigger in the Cordova context - which means that we do not receive the data payload of the notification in the application, thus we cannot direct the user appropriately once the app has been opened via tapping the notification.

I can see from the Xcode logs when testing on iOS that the payloads ARE getting to the UA SDK / plugin, but are NOT being bubbled to the application for some reason.

I can also see that we DO consistently receive the `urbanairship.deep_link` event.

### What is the expected behavior?
ℹ In all cases, the 'push' event is fired and received by the app, and forwarded to the Cordova context - when the notification is tapped - the 'notification_opened' event is fired and received by the app, also forwarded to the Cordova context - both with expected data payloads

### What are the steps to reproduce the unexpected behavior?
ℹ See above scenario. I've attached a Chrome log for the Android version - this is behaving as expected in all cases.

### Do you have logging for the issue?
ℹYep, attached a variety of screen grabs and logs.
![safari-log-push-not-received](https://user-images.githubusercontent.com/468638/58007935-3e209b80-7ae3-11e9-8cb9-b650c098bf7a.png)
<img width="1486" alt="chrome-android-log" src="https://user-images.githubusercontent.com/468638/58007622-93a87880-7ae2-11e9-98bd-14f9558eb1d5.png">
[x-code-push-not-received.log](https://github.com/urbanairship/urbanairship-cordova/files/3196988/x-code-push-not-received.log)
[xcode-push-received.log](https://github.com/urbanairship/urbanairship-cordova/files/3196989/xcode-push-received.log)

**Comment by rlepinski** [comment]
@chrisweight Do you have reliable way of reproducing this? I think I might see the problem, if I did some code changes in a branch could you try it out?

**Comment by chrisweight** [comment]
Yep, I can reproduce it consistently, let's go for it

**Comment by chrisweight** [comment]
@rlepinski / @crow - cheers for the fix, is there a patch release ETA for this?

**Comment by chrisweight** [comment]
👍 awesome!
