### ISSUE TITLE
Build error for android when we are adding new plugin https://github.com/TruewindIT/cordova-plugin-firebase#1.7

### ISSUE THREAD

**Issue by umeshk** [urbanairship/urbanairship-cordova#315]
❗For how-to inquiries involving Airship functionality or use cases, please
contact (support)[https://support.airship.com/].

# Preliminary Info

### What Airship dependencies are you using?
UA plugin Version 7.5.0

### What are the versions of any relevant development tools you are using?
UA plugin Version 7.5.0

# Report

### What unexpected behavior are you seeing?
We are seeing below error
* What went wrong:
A problem occurred evaluating project ':app'.
Failed to apply plugin [id 'com.google.gms.google-services']
Cannot add extension with name 'googleServices', as there is an extension already registered with that name.

### What is the expected behavior?
Please add plugin provided with URL along with UA plugin Version 7.5.0 and generate android build

### What are the steps to reproduce the unexpected behavior?
Please add plugin provided with URL along with UA plugin Version 7.5.0

### Do you have logging for the issue?
We are seeing below error
* What went wrong:
A problem occurred evaluating project ':app'.
Failed to apply plugin [id 'com.google.gms.google-services']
Cannot add extension with name 'googleServices', as there is an extension already registered with that name.

**Comment by crow** [comment]
@umeshk could you please provide the complete logging in which the "Failed to apply plugin [id 'com.google.gms.google-services']" error is embedded? 

It would also be useful to see how you are including the com.google.gms.google-services dependency in your gradle file.

Both these items would be helpful for troubleshooting the issue.

**Comment by umeshk** [comment]
Uploaded full logs.
Uploaded build-extra.gradle of UA plugin. It is not allowing to upload it with .gradle extension so added as a zip.
For build-extra.gradle of Firebase Plugin it gets added through this plugin https://github.com/TruewindIT/cordova-plugin-firebase#1.7


[MobileAppAndroidBuildLog.txt](https://github.com/urbanairship/urbanairship-cordova/files/3495459/MobileAppAndroidBuildLog.txt)

**Comment by crow** [comment]
It's not possible to use the Airship plugin alongside another firebase provider.

**Comment by umeshk** [comment]
@crow yes we are migrating from google analytics to firebase analytics.

**Comment by umeshk** [comment]
@crow I tried to use similar version of Google Services (com.google.gms:google-services:4.2.0) as that of Firebase plugin then build was successful but UA notifications are not working whereas Firebase notifications are working fine.
