### ISSUE TITLE
Push Notification Sounds overlaps

### ISSUE THREAD

**Issue by gonzalovinas** [urbanairship/urbanairship-cordova#321]
Hi there! I've a working app using cordova 8 and latest uaship libs.

It happens that I use a notification sound which is perhaps about 30 seconds long. Anytime in between any other push notification arrive the "long" sound gets chopped.

So... I created a new notification channel one for the "long" sound with HIGH IMPORTANTE and custom sound and another for the classical notifications sound without sound at all.. its uses default device notification sound..

The problem still persist. How can I make those 2 channels play independently their sounds. 

Thanks in advance.

**Comment by marc-scig** [comment]
Hi @gonzalovinas,

All the SDK does is configure the sound URI on the channel, there's no media playback code on our side. As far as I can tell, If the sounds are overlapping this is probably just standard Android behavior and there's not much we can do about it.
