### ISSUE TITLE
pod: Command failed with exit code 1

### ISSUE THREAD

**Issue by NikaZhenya** [urbanairship/urbanairship-cordova#341]
# Preliminary Info

MacOS 10.15.3
Cordova 9.0.0 (cordova-lib@9.0.1)
Cordova-ios 5.1.1
Cocoapods 1.9.1
Xcode 11.3.1 (11C504)

# Report

### What unexpected behavior are you seeing?

I can't install the plugin, even by remove it and adding again

### What is the expected behavior?

No pod errors

### What are the steps to reproduce the unexpected behavior?

```
$ pod repo update
Updating spec repo `cocoapods`

$ pod setup
Setup completed

$ cordova plugin add urbanairship-cordova
Installing "urbanairship-cordova" for android
Subproject Path: CordovaLib
Subproject Path: app
Installing "urbanairship-cordova" for browser
Installing "urbanairship-cordova" for ios
Running command: pod install --verbose
Failed to install 'urbanairship-cordova': Error: pod: Command failed with exit code 1
    at ChildProcess.whenDone (/Users/altagraciaac/Repositories/bdo-mexico/cordova/node_modules/cordova-common/src/superspawn.js:135:23)
    at ChildProcess.emit (events.js:311:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:443:11)
    at Socket.emit (events.js:311:20)
    at Pipe.<anonymous> (net.js:668:12)
pod: Command failed with exit code 1

$ cordova plugin remove urbanairship-cordova
Uninstalling urbanairship-cordova from android
Subproject Path: CordovaLib
Subproject Path: app
Uninstalling urbanairship-cordova from browser
js-module uninstall called : plugins/urbanairship-cordova/www/UrbanAirship.js
Uninstalling urbanairship-cordova from ios
Running command: pod install --verbose

[!] The Podfile does not contain any dependencies.

Removing "urbanairship-cordova"
Removing urbanairship-cordova from package.json

$ cordova plugin add urbanairship-cordova
Installing "urbanairship-cordova" for android
Subproject Path: CordovaLib
Subproject Path: app
Installing "urbanairship-cordova" for browser
Installing "urbanairship-cordova" for ios
Running command: pod install --verbose
Failed to install 'urbanairship-cordova': Error: pod: Command failed with exit code 1
    at ChildProcess.whenDone (/Users/altagraciaac/Repositories/bdo-mexico/cordova/node_modules/cordova-common/src/superspawn.js:135:23)
    at ChildProcess.emit (events.js:311:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:443:11)
    at Socket.emit (events.js:311:20)
    at Pipe.<anonymous> (net.js:668:12)
pod: Command failed with exit code 1

$ cordova plugins
cordova-plugin-inappbrowser 3.2.0 "InAppBrowser"
cordova-plugin-whitelist 1.3.4 "Whitelist"
cordova-support-google-services 1.3.2 "cordova-support-google-services"
urbanairship-cordova 10.1.1 "Urban Airship"

$ cordova platforms
Installed platforms:
  android 8.1.0
  browser 6.0.0
  ios 5.1.1
Available platforms: 
  electron ^1.0.0
  osx ^5.0.0
  windows ^7.0.0
 ```

**Comment by marc-scig** [comment]
Thanks @NikaZhenya,

We'll look into it shortly.

**Comment by crow** [comment]
I'm not currently able to reproduce this on the same dependency setup using the sample created by `scripts/create_sample.sh`.  The issue you're seeing usually indicates that cocoapods is having an issue finding or reading the spec from the local cocoapods repo. It looks like you've tried `pod repo update`, which follows the right line of reasoning. You might try running `pod repo update` again after running `pod setup`. Other than that, you might benefit from uninstalling and reinstalling the cocoapods tool itself.

**Comment by NikaZhenya** [comment]
FCC: imap://nika.zhenya%40perrotuerto.blog@sub4.mail.dreamhost.com/INBOX/Sent
X-Identity-Key: id1
X-Account-Key: account1
From: Nika Zhenya <nika.zhenya@perrotuerto.blog>
Subject: aviso de ausencia del 3 al 12 de abril
Message-ID: <7063a04a-8589-2e57-3570-177e1419db6e@perrotuerto.blog>
Autocrypt: addr=nika.zhenya@perrotuerto.blog; keydata=
 mQENBF5E9iUBCAC+iJ0s0/BIBYm8WaSSXs4KpmTdO4ho7cr+KdnRLsNINis2sM0wyQJFyjre
 1TVtuVqPTeIpTyaX0SQVQ44R2M8xr8gN6/s+vxXo6mNYvFaefdLp1diCSDTdWgNk3wcDdVya
 hoJavIfaQXxDNyrT1DW/EM53f/OIr05v2sItzweFJFf8Y2y6fhRMHo7ExyYK8haKUhBWBnS9
 +yh1SjQv/iT894IpSNLQfIIQxaVC1uR66jq+w+KGyoah8oOzpu2aK0iFxUC0yfeDLEz8mBk7
 WzG1jRw688emXMI3A4PxPFmhUWocNg00BnP/I5LuGmz0jcelabsIFem3DK0EcWRMWnv/ABEB
 AAG0Kk5pa2EgWmhlbnlhIDxuaWthLnpoZW55YUBwZXJyb3R1ZXJ0by5ibG9nPokBVAQTAQgA
 PhYhBLtC6sjySsVQagTOiyBwCDigM44oBQJeRPYlAhsDBQkDwmcABQsJCAcCBhUKCQgLAgQW
 AgMBAh4BAheAAAoJECBwCDigM44ocwkH/RnGZWfFGnX0esz7T4FYl0mc+1Ds7hFSXQnt8iSM
 6W8DdJcq4mVqrCIJHUvl3ur/dMtBxiE1bw6xymzDDRHH1T+Hzaz5+Mr6B6CeuHbechX3SwsR
--------------------

=> Este es un mensaje automatizado por lo que no es necesario responder.

Hola, del 3 al 12 de abril me encontraré de vacaciones, por lo que
no responderé a ningún correo.

¡Agradezco tu compresión!

-- 
Nika Zhenya <nika.zhenya@perrotuerto.blog>
Perro Tuerto / Programando LIBREros
www.perrotuerto.host
www.perrotuerto.blog

**Comment by NikaZhenya** [comment]
Well, I:

-  updated brew,
- ensured everything is ok with brew,
- updated ruby
- removed nodejs
- installed nvm
- installed lastest nodejs version with nvm
- installed cordova and
- installed cocoapods,

and I still have the same problem.

I did a manual `pod install --verbose` in `./platforms/ios` and I get the same error, but with this log:

```
$ pod install --verbose
  Preparing

Analyzing dependencies

Inspecting targets to integrate
  Using `ARCHS` setting to build architectures of target `Pods-BDO México`:
  (``)

Resolving dependencies of `Podfile`
[!] CocoaPods could not find compatible versions for pod "Airship":
  In Podfile:
    Airship (= 13.1.0)

Specs satisfying the `Airship (= 13.1.0)` dependency were found, but they required a higher minimum deployment target.

/Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:328:in `raise_error_unless_state'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:310:in `block in unwind_for_conflict'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:308:in `tap'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:308:in `unwind_for_conflict'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:684:in `attempt_to_activate'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:254:in `process_topmost_state'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:182:in `resolve'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolver.rb:43:in `resolve'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/resolver.rb:94:in `resolve'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer/analyzer.rb:1065:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer/analyzer.rb:1063:in `resolve_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer/analyzer.rb:124:in `analyze'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer.rb:410:in `analyze'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer.rb:235:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer.rb:234:in `resolve_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer.rb:156:in `install!'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/command/install.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

What does `[!] CocoaPods could not find compatible versions for pod "Airship":` means?

**Comment by rlepinski** [comment]
Well you found your issue. I wish cordova would bubble it better.

You need to set your deployment target to 11+. Our SDK only supports the last 3 versions of iOS.

**Comment by NikaZhenya** [comment]
I put `<preference name="deployment-target" value="13.2" />` in `config.xml` and now is building. But now I have another issue: `Module 'Airship' not found.` I am gonna close this one
