### ISSUE TITLE
E/UALib-Cordova: Action failed to execute: setUserNotificationsEnabled

### ISSUE THREAD

**Issue by flexaddicted** [urbanairship/urbanairship-cordova#342]
❗For how-to inquiries involving Airship functionality or use cases, please
contact (support)[https://support.airship.com/].

# Preliminary Info

### What Airship dependencies are you using?

urbanairship-cordova 10.1.0

### What are the versions of any relevant development tools you are using?

Cordova 9
Android Studio 3.4.2
Android 8.1.0
Android build tool 28.0.3
Android SDK 28

# Report

### What unexpected behavior are you seeing?

`setUserNotificationsEnabled ` fails to register in `com.urbanairship.cordova.UAirshipPlugin`.

### What is the expected behavior?

`setUserNotificationsEnabled ` should register correctly in `com.urbanairship.cordova.UAirshipPlugin`.

### What are the steps to reproduce the unexpected behavior?

Follow all the steps available in `README.md`.

### Do you have logging for the issue?

```
E/UALib-Cordova: Action failed to execute: setUserNotificationsEnabled
    java.lang.NoSuchMethodException: com.urbanairship.cordova.UAirshipPlugin.setUserNotificationsEnabled [class org.json.JSONArray, class org.apache.cordova.CallbackContext]
        at java.lang.Class.getMethod(Class.java:2069)
        at java.lang.Class.getDeclaredMethod(Class.java:2047)
        at com.urbanairship.cordova.UAirshipPlugin$1.run(SourceFile:153)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
```

**Comment by crow** [comment]
@flexaddicted thanks for reporting, will attempt to reproduce this now

**Comment by flexaddicted** [comment]
@crow Thank you for your quick reply.

**Comment by crow** [comment]
I'm not able to reproduce this using the sample. The android portion of the plugin implementation this error exception [comes from](https://github.com/urbanairship/urbanairship-cordova/blob/5fe45b28b1c4bb61c4f5817604a278922fad0e96/src/android/UAirshipPlugin.java#L153) is using reflection to get the method name.  What does your r8/proguard implementation look like?

**Comment by flexaddicted** [comment]
@crow Thanks for your reply. I'll disable ProGuard rules for Airship and let you know.

**Comment by flexaddicted** [comment]
@crow in our ProGuard file we are using the following but it does not work. Any suggestion?

```
### AIRSHIP
-keep class com.urbanairship.cordova.UAirshipPlugin.** { *; }
-keep public class com.urbanairship.UAirship
-keep public class com.urbanairship.AirshipConfigOptions
-keep public class com.urbanairship.push.PushMessage
```

**Comment by crow** [comment]
You can print the usage to see what Airship files are being removed (if any):

Add this to your custom rules file:
`-printusage <output-dir>/usage.txt
`

More info:
https://developer.android.com/studio/build/shrink-code.html#usage

**Comment by flexaddicted** [comment]
@crow After some investigations we fixed with

`-keep class com.urbanairship.** { *; }`

**Comment by crow** [comment]
@flexaddicted Glad you were able to resolve the issue. We'll look in to how we can improve this. Thanks for reporting.
