### ISSUE TITLE
iOS - urbanairship.push is not dispatched when app is in foreground

### ISSUE THREAD

**Issue by couchoud** [urbanairship/urbanairship-cordova#344]
# Preliminary Info

### What Airship dependencies are you using?

urbanairship-cordova 10.1.0

### What are the versions of any relevant development tools you are using?
cordova 9
cordova-ios 5.1.1
Xcode Version 11.3.1 (11C504)

# Report

### What unexpected behavior are you seeing?

The 'urbanairship.push' notifications are not dispatched when an iOS application is in the foreground. 

### What is the expected behavior?

An 'urbanairship.push' event should be dispatched when an application receives a notification while in the foreground. 

### What are the steps to reproduce the unexpected behavior?

1. Install/Setup Plugin (Standard configuration with UAirship.takeOff called manually)
1. Add listener for `urbanairship.push` event
2. Send test notification from Airship Test Push Notifications tool with an alert defined (with or without custom iOS overrides. Does not seem to make any different).

- I tried calling`UAirship.setPresentationOptions(UAirship.presentationOptions.alert)` and it makes no difference.

### Do you have logging for the issue?

Xcode logs the notification when received:

`2020-04-01 15:24:34.328826-0400 LEADxBeta[11432:4701364] [D] +[UAAppIntegration userNotificationCenter:willPresentNotification:withCompletionHandler:] [Line 80] Notification center will present notification: <UNNotification: 0x283d61d40; source: com.leadx.leadxBeta date: 2020-04-01 19:24:25 +0000, request: <UNNotificationRequest: 0x283d61bc0; identifier: A13FE4CE-137C-47EA-A5FE-FCAA88FD0190, content: <UNNotificationContent: 0x2808d51e0; title: (null), subtitle: (null), body: <redacted>, summaryArgument: , summaryArgumentCount: 0, categoryIdentifier: , launchImageName: , threadIdentifier: , attachments: (
), badge: (null), sound: (null), realert: 0, trigger: <UNPushNotificationTrigger: 0x2831d63c0; contentAvailable: NO, mutableContent: NO>>, intents: (
)>
`

The event handler on the javascript side is never triggered. I am however able to trigger the handler by dispatching my own event from the console, eg:

`document.dispatchEvent(new Event('urbanairship.push'))`

**Comment by BrianBatchelder** [comment]
Thanks for the report, @couchoud. We are looking into it and will get back to you as soon as possible.

**Comment by BrianBatchelder** [comment]
@couchoud : Do you know if you are receiving `urbanairship.push` events when the app is in the background?

**Comment by couchoud** [comment]
Hey, @BrianBatchelder - I'm receiving notifications while the app is in the background or not running at all. I'm also seeing the 'urbanairship.notification_opened' fire when the notification is clicked.

**Comment by BrianBatchelder** [comment]
Just to be clear: you are receiving neither notifications nor 'urbanairship.push` events when the app is in the foreground. No system notification alerts. Do you see an alert sent while you are in the foreground if you then background the app?

**Comment by BrianBatchelder** [comment]
I have been so far unable to reproduce your issue. It might help if you can answer a few more questions:

Do you ever remove the `urbanairship.push` event listener? In our sample app, we remove it when the app goes into the background ("pause" event), and add it back when the app goes into the foreground ("resume" event). Perhaps it is being removed and not re-added?

Also, take a look at your config.xml. Do you have this?
`<preference name="com.urbanairship.ios_foreground_notification_presentation_alert" value="false" />`
If so, that might be overriding your call to `callingUAirship.setPresentationOptions(UAirship.presentationOptions.alert)`. It is probably best to just set it true in your config.xml.

**Comment by couchoud** [comment]
Hi @BrianBatchelder - I was finally able to get the notifications to work. I think there may have been some sort of dependency issue that just wasn't making itself known. After I double-checked all the cases you suggested in your last comment I went ahead with yet another full rebuild of my environment and dependencies. After that, things started to work as expected. I appreciate your help on this. I'll be sure to comment on this thread if I notice anything.
