### ISSUE TITLE
Failed to build in Cordova 9.0 Android

### ISSUE THREAD

**Issue by maxkopych** [urbanairship/urbanairship-cordova#358]
Failed to capture fingerprint of input files for task ':app:preDebugBuild' property 'compileManifests' during up-to-date check.
In project 'app' a resolved Google Play services library dependency depends on another at an exact version (e.g. "[11.0.
  1]", but isn't being resolved to that version. Behavior exhibited by the library will be unknown.

  Dependency failing: com.google.android.gms:play-services-analytics-impl:11.0.1 -> com.google.android.gms:play-services-b
  asement@[11.0.1], but play-services-basement version was 17.2.1.

  The following dependencies are project dependencies that are direct or have transitive dependencies that lead to the art
  ifact with the issue.
  -- Project 'app' depends onto com.google.firebase:firebase-common@19.3.0
  -- Project 'app' depends onto com.google.android.gms:play-services-base@17.2.1
  -- Project 'app' depends onto com.google.android.gms:play-services-analytics-impl@11.0.1
  -- Project 'app' depends onto com.google.android.gms:play-services-tasks@17.0.2
  -- Project 'app' depends onto com.google.firebase:firebase-datatransport@17.0.3
  -- Project 'app' depends onto com.google.firebase:firebase-iid-interop@17.0.0
  -- Project 'app' depends onto com.google.android.gms:play-services-tagmanager-v4-impl@11.0.1
  -- Project 'app' depends onto com.google.android.gms:play-services-analytics@11.0.1
  -- Project 'app' depends onto com.google.firebase:firebase-installations-interop@16.0.0
  -- Project 'app' depends onto com.google.firebase:firebase-measurement-connector@18.0.0
  -- Project 'app' depends onto com.google.firebase:firebase-messaging@20.1.5
  -- Project 'app' depends onto com.google.firebase:firebase-iid@20.1.5
  -- Project 'app' depends onto com.urbanairship.android:urbanairship-fcm@13.1.2
  -- Project 'app' depends onto com.google.android.gms:play-services-stats@17.0.0
  -- Project 'app' depends onto com.google.android.gms:play-services-basement@17.2.1
  -- Project 'app' depends onto com.google.firebase:firebase-installations@16.2.1

  For extended debugging info execute Gradle from the command line with ./gradlew --info :app:assembleDebug to see the dep
  endency paths to the artifact. This error message came from the google-services Gradle plugin, report issues at https://
  github.com/google/play-services-plugins and disable by adding "googleServices { disableVersionCheck = false }" to your b
  uild.gradle file.

**Comment by BrianBatchelder** [comment]
@maxkopych: Could you please tell us why you think this failure is related to our plugin?

**Comment by maxkopych** [comment]
@BrianBatchelder Hi, sorry I am new to cordova. but it's look like it conflict with cordova-plugin-google-analytics plugin. Any suggestions how to fix that? Thank you!

**Comment by BrianBatchelder** [comment]
@maxkopych: It is quite difficult to debug this issue from the information you have given us. Can you help us by answering the following questions?

- Did you follow the instructions in our [README](https://github.com/urbanairship/urbanairship-cordova/blob/main/README.md), particularly this section on the [GoogleServicesPlugin](https://github.com/urbanairship/urbanairship-cordova#android-googleservicesplugin), and on our [docs site](https://docs.airship.com/platform/cordova/getting-started/)?
- What version of our plugin are you using? 
- What are the versions of any relevant development tools you are using?
- Did you report the message to Google via the url at the end of the message? 
- Is this a new app, or one that was building successfully before?
