### ISSUE TITLE
AirshipResources.bundle not found

### ISSUE THREAD

**Issue by premedios** [urbanairship/urbanairship-cordova#360]
❗For how-to inquiries involving Airship functionality or use cases, please
contact (support)[https://support.airship.com/].

# Preliminary Info

### What Airship dependencies are you using?

Branch Mobile-648

### What are the versions of any relevant development tools you are using?

Cordova 7.1.0

# Report

### What unexpected behavior are you seeing?
```cordova build ios``` cannot generate AirshipResources.bundle

### What is the expected behavior?
It should be generating, or not, AirshipResources.bundle

### What are the steps to reproduce the unexpected behavior?
- 
- Created an empty cordova app, added the ios platform (5.1.1) and the urbanairship cordova plugin (branch Mobile-648)
- Run ```cordova build ios```

### Do you have logging for the issue?

[Error message](https://gist.github.com/premedios/78ec4673ea543dda7d7176a46caae051)

**Comment by BrianBatchelder** [comment]
@premedios : The MOBILE-* branches are development branches. They are not guaranteed to work and can be removed at any time. Please only install the plugin using the instructions in the README. If you must install from the repo, please use a tagged release as those have been verified to work correctly.
