### ISSUE TITLE
2 errors when building with Xcode 12

### ISSUE THREAD

**Issue by gibatronic** [urbanairship/urbanairship-cordova#361]
# Preliminary Info

### What Airship dependencies are you using?
`urbanairship/urbanairship-cordova 11.0.1`

### What are the versions of any relevant development tools you are using?
`Xcode 12`

# Report

### What unexpected behavior are you seeing?
2 semantic errors:
1. `UAMessageCenterSplitViewController.m` :: `setStyle`
    > Use of undeclared identifier '_style'; did you mean 'style'?
2. `UADefaultMessageCenterSplitViewController.m` :: `setStyle`
    > Use of undeclared identifier '_style'; did you mean 'style'?

### What is the expected behavior?
To build without errors.

### What are the steps to reproduce the unexpected behavior?
Build a project using Xcode 12.

### Do you have logging for the issue?
N / A

**Comment by rlepinski** [comment]
We will try to get a release out ASAP. Here is the release PR - https://github.com/urbanairship/urbanairship-cordova/pull/362

**Comment by gibatronic** [comment]
I just upgraded the plugin to `12.0.0` but still got the same errors.

**Comment by gibatronic** [comment]
Closing this since it was handled in urbanairship/ios-library#249
