### ISSUE TITLE
What is the plan for HMS supports for cordova

### ISSUE THREAD

**Issue by ashishdimi09** [urbanairship/urbanairship-cordova#367]

**Comment by rlepinski** [comment]
@ashishdimi09 You are the first to request HMS. We have plans to turn our repo into a mono repo so we can provide additional plugins. Right now you can enable HMS by providing a custom [build-extras.gradle](https://cordova.apache.org/docs/en/latest/guide/platforms/android/#extending-buildgradle). You will need to add HMS, AGConnect, and Airship's HMS module: 

```
repositories {
    google()
    jcenter()
    maven {url 'https://developer.huawei.com/repo/'}
}

buildscript {
    dependencies {
        classpath 'com.huawei.agconnect:agcp:1.4.2.301'
    }
}

dependencies {
    implementation "com.urbanairship.android:urbanairship-hms:14.1.2"
    implementation "com.huawei.hms:push:5.0.4.302"
}

apply plugin: 'com.huawei.agconnect'
```

Then you will need to add your agconnect-services.json like you do with your google-services.json file:

```
       <platform name="android">
            ...
            <resource-file src="google-services.json" target="app/agconnect-services.json " />
       </platform>
```

For additional setup instructions on how to setup the provider in Airship's dashboard, see  https://docs.airship.com/platform/android/getting-started/#hms

**Comment by rlepinski** [comment]
We have an HMS plugin now that you can use.
