### ISSUE TITLE
While creating build getting error - "Task :app:processDebugGoogleServices FAILED"

### ISSUE THREAD

**Issue by amitkumars96** [urbanairship/urbanairship-cordova#370]
While creating the build I am getting this issue. 

> Task :app:processDebugGoogleServices FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':app:processDebugGoogleServices'.
> File google-services.json is missing. The Google Services Plugin cannot function without it.

And dependencies are as follow:
    "cordova-android": "^9.0.0",
    "cordova-android-support-gradle-release": "^3.0.1",
    "cordova-plugin-calendar": "^5.1.5",
    "cordova-plugin-camera": "^5.0.1",
    "cordova-plugin-device": "^2.0.3",
    "cordova-plugin-dialogs": "^2.0.2",
    "cordova-plugin-file": "^6.0.2",
    "cordova-plugin-file-transfer": "^1.7.1",
    "cordova-plugin-geolocation": "^4.0.2",
    "cordova-plugin-inappbrowser": "^4.0.0",
    "cordova-plugin-network-information": "^2.0.2",
    "cordova-plugin-screen-orientation": "^3.0.2",
    "cordova-plugin-splashscreen": "^6.0.0",
    "cordova-plugin-statusbar": "^2.4.3",
    "cordova-plugin-whitelist": "^1.3.4",
    "cordova-sqlite-storage": "^5.1.0",
    "elementtree": "^0.1.7",
    "es6-promise-plugin": "^4.2.2",
    "lodash": "^4.17.20",
    "phonegap-plugin-barcodescanner": "^8.1.0",
    "plist": "^3.0.1",
    "urbanairship-cordova": "^12.0.1"

Please help me out I am new to cordov and how i can resolve this issue?

**Comment by marc-scig** [comment]
Hi @amitkumars96,

The google-services.json file is a necessary part of the build. See [Getting Started](https://docs.airship.com/platform/cordova/getting-started/) for more info on setting up the cordova plugin, as well as the [FCM Setup Instructions](https://docs.airship.com/platform/android/getting-started/#fcm-configure-airship-dashboard).
