### ISSUE TITLE
urbanairship.push event not triggered for silent notification

### ISSUE THREAD

**Issue by AE1NS** [urbanairship/urbanairship-cordova#389]
# Preliminary Info

### What Airship dependencies are you using?
"@awesome-cordova-plugins/urbanairship": "5.41.0"
"urbanairship-cordova": "14.0.0"

### What are the versions of any relevant development tools you are using?
"@capacitor/android": "3.4.3"
"@capacitor/core": "3.4.3"

# Report

### What unexpected behavior are you seeing?
Android:
I am listening to the "urbanairship.push" event. When I go to the airship dashboard and send a default notification with title and body, I receive the message in the listener while the app is opened. I also see a console output, that the event was triggered. When I send a silent notification with the airship dashboard, no listener is triggered and I dont see any output in the console that an event has triggered ("Firing document event: urbanairship.push"). The silent notification dont have any special config. I just put in the named user and continue the wizard to the last step and put a custom key with key "test1" and value "test2". The airship dashboard marks the notification as "sent".

### What is the expected behavior?
If I understand it correctly, the "urbanairship.push" event should be triggered.

### What are the steps to reproduce the unexpected behavior?
Install the latest urbainairship-cordova version, listen to the "urbanairship.push" event and send a silent notification with the airship dashboard.

**Comment by rlepinski** [comment]
This is a limitation with cordova apps where the context is not available until the activity is created. You will have to use native code to process notifications in the background.

**Comment by AE1NS** [comment]
Thank you for your response. Does this mean, that the point when capacitor calls the initialize method of the a cordova plugin results in a missing activity reference?
https://github.com/urbanairship/urbanairship-cordova/blob/main/urbanairship-cordova/src/android/UAirshipPlugin.java#L134

Do you think this should only be fixed on capacitors side, or does it maybe make sense to implement something in this cordova plugin to fix this? Maybe a method that can be called afterwards to fix the context or a check inside the "execute" method, that sets the context of its null. I know this sounds like a less beautiful solution, but since the capacitor community is growing, it would be nice to use all features of this plugin.

**Comment by rlepinski** [comment]
Sorry, I used a term that was overloaded. When I said context, I meant the cordova context - js interface and plugins. If you take a look at capacitor, everything is setup in the activity instead of the application so its not a limitation with this plugin but capacitor - https://github.com/ionic-team/capacitor/blob/main/android/capacitor/src/main/java/com/getcapacitor/BridgeActivity.java

I don't see any docs about any kind of headless JS tasks and if you look at the capacitor push plugin, they also have the same limitation - https://capacitorjs.com/docs/apis/push-notifications#silent-push-notifications-data-only-notifications

> This plugin does support data-only notifications, but will NOT call pushNotificationReceived if the app has been killed. To handle this scenario, you will need to create a service that extends FirebaseMessagingService, see [Handling FCM Messages](https://firebase.google.com/docs/cloud-messaging/android/receive).

What are you trying to accomplish with a background push? I might be able to help you work around this limitation.

**Comment by AE1NS** [comment]
> This plugin does support data-only notifications, but will NOT call pushNotificationReceived if the app has been killed.

My issue is pointing to the foreground state. My listener is not firing for data notifications while the app is opened.

> What are you trying to accomplish with a background push? I might be able to help you work around this limitation.

We are using the capacitor push notifications in our production app right now and we want to refactor everything to airship. 

**Example use case:**
We have a process with 2 steps. The user starts the process with the app and is now waiting for a event by the server to continue. At the moment we send a push notification with extras, that contains the information to continue to step 2.

So when the app is in the background, the user receives a default push that tells him, that step 2 is entered and the user can click on it to get redirected to that page in the app.

When the app is in the foreground, the capacitor push notification plugin does not show the push in the system notification center, but will only enter a JS callback. Inside this callback I evaluate the extras and if the user is currently waiting in step 1, he automatically gets redirected to step 2.

With airship I had the following idea: On long term our backend would just send events to airship, so all "visible" push notifications could be sent by the airship dashboard. But to implement our "app foreground" handling of switching step 1 to step 2, I thought about using data pushes. And when the app is killed or in the background, its no problem for me that the data push is not received, because the user hat a default push in the notification center.

I know that an alternative way would be a websocket connection, but I am not sure if its a good idea to use websockets inside native apps.

**Comment by rlepinski** [comment]
Ahh I see, I misread the issue. I thought you wanted silent push in a killed state.

Ill reopen and investigate. Could you provide your code that you are using to listen for notifications, I just need simple listener calls and where in your apps lifecycle that you are making them

**Comment by rlepinski** [comment]
Actually I see the issue, nothing is listening for the push received callback. We will fix it in the next release

**Comment by rlepinski** [comment]
I got a branch up if you wanna try it out. My cordova environment is not in a good place right now, so it will have to wait for the morning for me (PST)

**Comment by AE1NS** [comment]
Looks good, now the listener is fired. Thank you for fixing this so fastly!
