### ISSUE TITLE
Read the 'actions' from a push

### ISSUE THREAD

**Issue by AE1NS** [urbanairship/urbanairship-cordova#393]
Inside the listener for the event 'urbanairship.push' I get the notification as parameter. I can just read properties like 'title' and 'message' from it, but would it also be possible to read the 'actions'?

We want to achieve a fallback when a push is received and the user is inside the app at that moment.
I.e.: The user is on the start page and receives a push. In this moment, I would like to read the action (i.e. deeplink) from the received push, so I could show an html alert and could redirect the user to this page.
A solution would be the custom keys to store the 'path', thats our current solution, but I would prefer to get the actions data. Because a non technical employee could use airship to create pushes, without adding additional custom keys, that needs additional documentations.

Additional question: When the user is inside the app and receives a push, does Android show a push in the system notification center and iOS doesnt? In our previous implementation (using capacitors push notifications), I never got a system notification center entry in Android, while the user had the app opened. Thats also a point, why I would like to use the fallback inside the app.

**Comment by rlepinski** [comment]
I think that should be possible. On iOS you probably already have the actions in the extras but on Android you do not.

Android by default will show a notification in the center, but you can control it with sending the extra `com.urbanairship.foreground_display`: `true`. iOS its controlled by foreground presentation options. 

I can probably throw together something real fast if you want to test it out.

**Comment by rlepinski** [comment]
Started this branch: https://github.com/urbanairship/urbanairship-cordova/tree/GH-393

My xcode is freezing so I need to figure that out before I can do the iOS action parsing. Also need to run some tests on Android to make sure it all works as expected

**Comment by rlepinski** [comment]
https://github.com/urbanairship/urbanairship-cordova/pull/394

**Comment by AE1NS** [comment]
I see the 'action' property in the notification now, but its content seems wrong. Its always 'actions: {^d: null}'.

Regarding the foreground notification: Did you have a typo? Because you mentioned `com.urbanairship.foreground_display` but added `com.urbanairship.foreground_notifications` in the code. I tried to add it to the cordova preferences/settings but I still get a system notification while the app is in foreground.

**Comment by rlepinski** [comment]
That is just the storage value, it does not need to match the notification value. I will take a look at the actions issue

**Comment by rlepinski** [comment]
@AE1NS pushed a change to fix the actions being null

**Comment by AE1NS** [comment]
Ok thanks! What about foreground display? How exactly can I use this config? Do I just have to set the cordova plugin config `com.urbanairship.foreground_display` to false?
In my case (because I am using capacitor) I have to set this config inside my [capacitor.config.ts](https://capacitorjs.com/docs/config):
```
"cordova": {
    "preferences": {
        "com.urbanairship.production_app_key": "...",
        "com.urbanairship.production_app_secret": "...",
        "com.urbanairship.development_app_key": "...",
        "com.urbanairship.development_app_secret": "...",
        "com.urbanairship.in_production": "false",
        "com.urbanairship.development_log_level": "debug",
        "com.urbanairship.production_log_level": "error",
        "com.urbanairship.auto_launch_message_center": "true",
        "com.urbanairship.site": "EU",
        "com.urbanairship.foreground_display": "false"
    }
}
```
All configs are working fine, but I still get a system notification while the app is in foreground.

**Comment by rlepinski** [comment]
You can enable/disable it through JS. We persist the value so you only have to call it once. `UAirship.setAndroidForegroundNotificationsEnabled(true)`

**Comment by AE1NS** [comment]
`UAirship.setAndroidForegroundNotificationsEnabled(true)` looks good! Thank you!

Regarding the actions property, I see the deep link url now, but the key of the object looks strange. Is this intended to be ^d?
`actions: {^d: 'https://...'}`

**Comment by AE1NS** [comment]
Ok I see. Thanks for your fast replies!
