### ISSUE TITLE
Android build failed when I installed plugin urbanairship-cordova together with cordova-plugin-fcm-with-dependecy-updated 

### ISSUE THREAD

**Issue by YaroslavG** [urbanairship/urbanairship-cordova#415]
Hello,
 I try to install your plugin in my project and it was added successfully. But when I start the android build - it failed. Is it even possible that these two plugins can be used together?

Error logs:

> Build file 'app/platforms/android/app/build.gradle' line: 349
> What went wrong:
> A problem occurred evaluating project ':app'.
> Failed to apply plugin 'com.google.gms.google-services'.
   > Cannot add extension with name 'googleServices', as there is an extension already registered with that name.

**Comment by rlepinski** [comment]
What versions are you on?

**Comment by YaroslavG** [comment]
After updating the FCM plugin build was successful.
