### ISSUE TITLE
airship shapes.swift does not compile

### ISSUE THREAD

**Issue by dmitryya-tr** [urbanairship/urbanairship-cordova#416]
❗For how-to inquiries involving Airship functionality or use cases, please
contact (support)[https://support.airship.com/].

# Preliminary Info

### What Airship dependencies are you using?
using urbanairship-cordova 14.6.0

### What are the versions of any relevant development tools you are using?
node 16.3
cordova 10 
mac os 13.4.1
xcode 14.3.1 

# Report

### What unexpected behavior are you seeing?
cordova build is failing with error 
### What is the expected behavior?
compile successfully 
### Do you have logging for the issue?
The following build commands failed:
        SwiftCompile normal x86_64 Compiling\ Sections.swift,\ Semaphore.swift,\ Shapes.swift,\ ShareAction.swift,\ ShareActionPredicate.swift,\ SMSRegistrationOptions.swift,\ StateController.swift,\ SubscriptionListAction.swift,\ SubscriptionListActionPredicate.swift,\ SubscriptionListAPIClient.swift,\ SubscriptionListEditor.swift,\ SubscriptionListFetchResponse.swift,\ SubscriptionListUpdate.swift,\ SystemVersion.swift,\ TagEditor.swift,\ TagGroupMutations.swift,\ TagGroupsEditor.swift,\ TagGroupUpdate.swift,\ TagsActionPredicate.swift,\ TaskManager.swift,\ TaskManagerProtocol.swift,\ TaskRequestOptions.swift,\ TextInput.swift,\ Thomas.swift /path/platforms/ios/Pods/Airship/Airship/AirshipPreferenceCenter/Source/data/Sections.swift /path/platforms/ios/Pods/Airship/Airship/AirshipCore/Source/Semaphore.swift /path/platforms/ios/Pods/Airship/Airship/AirshipCore/Source/Shapes.swift /path/platforms/ios/Pods/Airship/Airship/AirshipCore/Source/ShareAction.swift /path/platforms/ios/Pods/Airship/Airship/AirshipCore/Source/ShareActionPredicate.swift /path/platforms/ios/Pods/Airship/Airship/AirshipCore/Source/SMSRegistrationOptions.swift /path/platforms/ios/Pods/Airship/Airship/AirshipCore/Source/StateController.swift /path/platforms/ios/Pods/Airship/Airship/AirshipCore/Source/SubscriptionListAction.swift /path/platforms/ios/Pods/Airship/Airship/AirshipCore/Source/SubscriptionListActionPredicate.swift /path/platforms/ios/Pods/Airship/Airship/AirshipCore/Source/SubscriptionListAPIClient.swift /path/platforms/ios/Pods/Airship/Airship/AirshipCore/Source/SubscriptionListEditor.swift /path/platforms/ios/Pods/Airship/Airship/AirshipCore/Source/SubscriptionListFetchResponse.swift /path/platforms/ios/Pods/Airship/Airship/AirshipCore/Source/SubscriptionListUpdate.swift /path/platforms/ios/Pods/Airship/Airship/AirshipCore/Source/SystemVersion.swift /path/platforms/ios/Pods/Airship/Airship/AirshipCore/Source/TagEditor.swift /path/platforms/ios/Pods/Airship/Airship/AirshipCore/Source/TagGroupMutations.swift /path/platforms/ios/Pods/Airship/Airship/AirshipCore/Source/TagGroupsEditor.swift /path/platforms/ios/Pods/Airship/Airship/AirshipCore/Source/TagGroupUpdate.swift /path/platforms/ios/Pods/Airship/Airship/AirshipCore/Source/TagsActionPredicate.swift /path/platforms/ios/Pods/Airship/Airship/AirshipCore/Source/TaskManager.swift /path/platforms/ios/Pods/Airship/Airship/AirshipCore/Source/TaskManagerProtocol.swift /path/platforms/ios/Pods/Airship/Airship/AirshipCore/Source/TaskRequestOptions.swift /path/platforms/ios/Pods/Airship/Airship/AirshipCore/Source/TextInput.swift /path/platforms/ios/Pods/Airship/Airship/AirshipCore/Source/Thomas.swift (in target 'Airship' from project 'Pods')
        SwiftCompile normal x86_64 /path/platforms/ios/Pods/Airship/Airship/AirshipCore/Source/Shapes.swift (in target 'Airship' from project 'Pods')
(2 failures)

**Comment by rlepinski** [comment]
You will need to update the plugin to 14.9 or newer (I think). Definitely fixed in the latest 14.10.1
