### ISSUE TITLE
CDVPlugin class AirshipCordova (pluginName: AirshipCordova) does not exist.

### ISSUE THREAD

**Issue by MaximBelov** [urbanairship/urbanairship-cordova#424]
# Preliminary Info
Error: The plugin does not exist  if the name contains the space `Airship Cordova`
https://cordova.apache.org/docs/en/12.x/config_ref/#name

### What Airship dependencies are you using?

Codebase from 
https://github.com/urbanairship/urbanairship-cordova/pull/423

### What are the versions of any relevant development tools you are using?

xCode 15.2
cordova 12
cordova-ios 7.0.1
pod 1.15.2

# Report

### What unexpected behavior are you seeing?

<img width="1134" alt="Airship Cordova — Airship Cordova xcworkspace 2024-04-16 16-37-02" src="https://github.com/urbanairship/urbanairship-cordova/assets/7757752/42f620bd-05ab-48d3-8c23-bdbc9b4ae16b">
<img width="731" alt="urbanairship-cordova – config xml 2024-04-16 16-37-35" src="https://github.com/urbanairship/urbanairship-cordova/assets/7757752/bfa40aa1-1690-42fd-860e-4d96b6056c13">

### What is the expected behavior?

Plugin should work with name contains space as name without  space

![AirshipCordova — AirshipCordova xcodeproj 2024-04-16 16-41-18](https://github.com/urbanairship/urbanairship-cordova/assets/7757752/2fd610f0-3c51-4ba5-8108-4b343624e449)

### What are the steps to reproduce the unexpected behavior?

Set value for tag `name` with space
`
<widget ...>
   <name>Airship Cordova</name>
</widget>
`

**Comment by rlepinski** [comment]
What issue is this causing?

**Comment by MaximBelov** [comment]
Api from the plugin AirshipCordova is not available 
if app name contains space  <widget ...> <name>**Airship Cordova**</name> </widget>

Xcode Debug output
`CDVPlugin class AirshipCordova (pluginName: AirshipCordova) does not exist`

**Comment by rlepinski** [comment]
Cool, get it taken care of today/tomorrow. We are working on an 18.1 release of the iOS SDK that we will use in next update.

Any reason this was not obvious in the sample app we have?

**Comment by MaximBelov** [comment]
https://github.com/urbanairship/urbanairship-cordova/blob/main/.github/workflows/CI.yaml

**Comment by MaximBelov** [comment]
Reproduce 
1. Change name to Test Airship 
https://github.com/urbanairship/urbanairship-cordova/blob/8a3f7b1a4989c5b9908b254a9e36609fe073d769/config_sample.xml#L7
2. Create ios app 
3. Run on device

**Comment by rlepinski** [comment]
The CI is not that awesome, just does bare minimum to make sure things build. I was running it locally though and didnt notice. Ill try your steps. Thank you!

**Comment by rlepinski** [comment]
What a weird error. Fixed if I add this to the plugin:
```
@objc(AirshipCordova)
```

**Comment by MaximBelov** [comment]
Fixed 
Thank you
