### ISSUE TITLE
Missing Changelog for Version 16.0.0

### ISSUE THREAD

**Issue by omgitsjan** [urbanairship/urbanairship-cordova#435]
# Report

### What unexpected behaviour are you seeing?
It appears that Version 16.0.0 of the Airship Cordova plugin does not have a changelog. When reviewing the commits, I could only find a changelog entry for Version 15.3.0, which was never released. The changelog for Version 16.0.0 is also not available in the GitHub release tab or in the official documentation (https://docs.airship.com/platform/mobile/resources/changelogs/cordova-changelog/).

### What is the expected behaviour?
I would expect a changelog for Version 16.0.0 to be available, providing a quick overview of the changes made in this major release. This would ideally be accessible either in the GitHub release tab or the documentation.

**Comment by rlepinski** [comment]
Hi, its actually whats listed as 15.3.0 in the changelog. I changed the version in the release from 15.3 to 16.0 but forgot to update the changelog version. Ill get that fixed today.

**Comment by rlepinski** [comment]
Should be updated in all the places now.
